trigger: none 
pool:
  vmImage: ubuntu-latest 

steps:
  - checkout: self

  # Instalar HawkScan en funci칩n de las variables configuradas
  - task: HawkScanInstall@1
    inputs:
      version: "4.0.3"
      installerType: "zip"  # auto
      installPath: $(if and(eq(variables['installerType'], 'auto'), eq(variables['vmImage'], 'ubuntu-latest')), '/home/vsts/custom', '')
    condition: always()

  # Ejecutar HawkScan para an치lisis de vulnerabilidades
  - task: RunHawkScan@1
    inputs:
      configFile: "stackhawk.yml"
      version: "4.0.3"
    env:
      HAWK_API_KEY: $(HAWK_API_KEY)
      APP_ENV: $(vmImage)  
      APP_ID: $(appId2)  
      SARIF_ARTIFACT: true  
    condition: always()

  # (Opcional) Escaneo de seguridad con Snyk
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'SnykTest'  # Conexi칩n a Snyk
      testType: 'code'  # Tipo de an치lisis
      failOnIssues: false  # No fallar en caso de encontrar problemas
      projectName: 'Test10'  # Nombre del proyecto
    condition: always()
