strategy:
  matrix:
    linux-zip:
      imageName: "ubuntu-latest"
      installerType: "zip"

pool:
  vmImage: $(imageName)

trigger: none

steps:
  - checkout: self


  # install the latest version of hawkscan
  - task: HawkScanInstall@1
    inputs:
      version: "4.3.0"
      installerType: "$(installerType)"

  # azure pipelines default jdk is 8, so we upgrade to 11 to run JavaSpringVulny
  # the hawkscan msi bundles java with it, so this step isn't necesarry for running HawkScan
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "17"
      jdkArchitectureOption: "x64"
      jdkSourceOption: "PreInstalled"

  # run hawkscan with the StackHawk Azure Extension
  - task: RunHawkScan@1
    inputs:
      configFile: "stackhawk.yml"
      version: "4.3.0"
    env:
      HAWK_API_KEY: $(HAWK_API_KEY) # use variables in the azure devops ui to configure secrets and env vars
      APP_ENV: $(imageName)
      APP_ID: $(appId2)
      SARIF_ARTIFACT: true

  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'SnykTest'
      testType: 'code'
      failOnIssues: false
      projectName: 'Test10'